language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '8'
  - '7'
  - '6'
branches:
  only:
    - master
before_install:
  # add yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn run lint
  - yarn run test
  - yarn run build
