language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '7'
  - '6'
branches:
  only:
    - master
before_script:
  - yarn clean
  - yarn install --prefer-offline
script:
  - npm run lint
  - npm run test
  - npm run build
